title: UserFrosting
metadata:
    description: 'Learn how to get started with UserFrosting to build your user-centered web application in PHP.'
    msapplication-config: 'https://learn.userfrosting.com/user/themes/sitetheme/images/browserconfig.xml'
    theme-color: 'ffffff'

taxonomies: [category,tag]
summary:
  size: 300

redirects:
    /basics/overview: /installation
    /basics/installation: /installation
    /basics/requirements: /installation/requirements
    /basics/requirements/basic-stack: /installation/requirements/basic-stack
    /basics/requirements/essential-tools-for-php: /installation/requirements/essential-tools-for-php
    /basics/requirements/develop-locally-serve-globally: /background/develop-locally-serve-globally
    /basics/getting-help: /troubleshooting/getting-help
    /background/client-side: /troubleshooting/debugging
    /background/server-side: /troubleshooting/debugging
    /building-pages: /recipes/creating-a-new-page
    /building-pages/templating-with-twig: /templating-with-twig
    /building-pages/assets: /asset-management
    /building-pages/assets/basic-usage: /asset-management
    /building-pages/assets/asset-bundles: /asset-management/asset-bundles
    /building-pages/assets/compiled-assets: /asset-management/compiled-assets
    /error-handling: /advanced/error-handling
    /other-services/cache: /advanced/cache
    /going-live/seo: /background/seo
    