title: UserFrosting
metadata:
    description: 'Learn how to get started with UserFrosting to build your user-centered web application in PHP.'
    msapplication-config: 'https://learn.userfrosting.com/user/themes/sitetheme/images/browserconfig.xml'
    theme-color: 'ffffff'

taxonomies: [category,tag]
summary:
  size: 300

redirects:
    /basics/installation: /installation
    /basics/requirements/basic-stack: /installation/requirements/basic-stack
    /basics/requirements/essential-tools-for-php: /installation/requirements/essential-tools-for-php
    /basics/requirements/develop-locally-serve-globally: /background/develop-locally-serve-globally
    /basics/getting-help: /troubleshooting/getting-help
