branches:
    'latest':
        path: ''
        label: 'Latest'
    '4.0':
        path: '/4.0'
        label: '4.0'
    '4.1':
        path: '/4.1'
        label: '4.1'
    '4.2':
        path: '/4.2'
        label: '4.2 Beta'
    'develop':
        path: '/develop'
        label: 'Develop'
